    [tool.black]
    py36 = true
    line-length = 95

    include = '\.pyi?$'
    exclude = '''
    /(
        \.git
      | \.venv
      | _build
      | buck-out
      | build
      | dist
      | \.github
      | \.idea
      | \.htmlcov

      # The following are specific to Black, you probably don't want those.
      | blib2to3
      | tests/data
    )/