    [build-system]
    requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

    [tool.setuptools_scm]
    write_to = "esofile_reader/version.py"

    [tool.black]
    line-length = 96

    include = '\.pyi?$'
    exclude = '''
    /(
        \.git
      | \.venv
      | _build
      | buck-out
      | build
      | dist
      | \.github
      | \.idea
      | \.htmlcov

      # The following are specific to Black, you probably don't want those.
      | blib2to3
      | tests/data
    )/


