name: Build

on:
  pull_request:
    types: [ closed ]
    branches:
      - master
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
if: github.event.pull_request.merged
  steps:
      - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.8'

        - name: Set up Poetry
          run: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            echo "$HOME/.poetry/bin" >> $GITHUB_PATH

        - name: Configure poetry
          run: poetry config virtualenvs.in-project true

        - name: Install dependencies
          run: poetry install

        - name: Install extras
          run: poetry install --extras "sql"

        - name: Build
          run: poetry build

        - name: Upload math result for job 1
          uses: actions/upload-artifact@v1
          with:
            name: dist
            path: dist
